In [1]:
import numpy as np

# Практическое задание №5

## 5.1.

**1) Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.**

In [2]:
# вот вектор Nх1
a = np.array([[i for i in range(5)]])
b = np.array([[i for i in range(1, 5)]], float).T
print(f'вектор a = \n{a}\n\nвектор b = \n{b}')
print(f'\nу вектора а строк: {a.shape[0]} и столбцов: {a.shape[1]}')
print(f'у вектора b строк: {b.shape[0]} и столбцов: {b.shape[1]}\n')
print(f'применим к ним фишку сложения на Python, используя логику сложения broadcasting:\na+b = \n{a+b}')

вектор a = 
[[0 1 2 3 4]]

вектор b = 
[[1.]
 [2.]
 [3.]
 [4.]]

у вектора а строк: 1 и столбцов: 5
у вектора b строк: 4 и столбцов: 1

применим к ним фишку сложения на Python, используя логику сложения broadcasting:
a+b = 
[[1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]
 [4. 5. 6. 7. 8.]]


In [3]:
# вот вектор 1хN
a = np.array([[4, 5, 6]])
a

array([[4, 5, 6]])

In [4]:
# умножим его на скаляр
np.dot(a, 8)

array([[32, 40, 48]])

In [5]:
# скалярное произведение
a = np.array([1, 2, 3, 4, 5], float)
b = np.array([0, 9, 8, 7, 6], float)
np.inner(a, b)

100.0

In [6]:
# умножение по законам матрицы
a = np.array([7, 8, 9], float)
b = np.array([9, 8, 7], float)
np.outer(a, b)

array([[63., 56., 49.],
       [72., 64., 56.],
       [81., 72., 63.]])

**2) Вычислите, по возможности не используя программирование: $(5E)^{-1}$ где Е – единичная матрица размера 5х5.**

$(5E)^{-1} =$ $\frac{1}{5^1} \cdot \begin{bmatrix}
1 & 0 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 \\
\end{bmatrix} =$ $\ 0.2 \cdot \begin{bmatrix}
1 & 0 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 \\
\end{bmatrix} =$ 
$\begin{bmatrix}
0.2 & 0 & 0 & 0 & 0 \\
0 & 0.2 & 0 & 0 & 0 \\
0 & 0 & 0.2 & 0 & 0 \\
0 & 0 & 0 & 0.2 & 0 \\
0 & 0 & 0 & 0 & 0.2 \\
\end{bmatrix}$

проверим за собой на Python:

In [7]:
A = 5* np.eye(5)
print(f'A*5 =\n{A}\n\nобратная матрица для A =\n{np.linalg.inv(A)}')

A*5 =
[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]

обратная матрица для A =
[[ 0.2  0.   0.   0.   0. ]
 [ 0.   0.2  0.   0.   0. ]
 [ 0.   0.   0.2  0.   0. ]
 [-0.  -0.  -0.   0.2 -0. ]
 [ 0.   0.   0.   0.   0.2]]


## 5.2.

**Вычислите определитель:**

$\Delta \begin{bmatrix}
1 & 2 & 3 \\
4 & 0 & 6 \\
7 & 8 & 9 \\
\end{bmatrix} = 
1 \cdot \begin{bmatrix}
0 & 6 \\
8 & 9 \\
\end{bmatrix} - 
2 \cdot \begin{bmatrix}
4 & 6 \\
7 & 9 \\
\end{bmatrix} +
3 \cdot \begin{bmatrix}
4 & 0 \\
7 & 8 \\
\end{bmatrix} =
1(0 \cdot 9 - 6 \cdot 8) - 2(4 \cdot 9 - 6 \cdot 7) + 3( 4 \cdot 8 - 0 \cdot 7) = -48 - 72 + 84 + 96 = 60
$ 

и по питоновски:

In [8]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
print(f'матрица A =\n{A}\n\nОпределитель матрицы A = {np.round(np.linalg.det(A))}')

матрица A =
[[1 2 3]
 [4 0 6]
 [7 8 9]]

Определитель матрицы A = 60.0


## 5.3.

**1) Вычислите матрицу, обратную данной:**

$\begin{bmatrix}
1 & 2 & 3 \\
4 & 0 & 6 \\
7 & 8 & 9 \\
\end{bmatrix}$

считаем по формуле $A^{-1} = \frac{A_*^T}{\Delta A}$ где:

$A^{-1}$ - обратная матрица

$A_*^T$ - транспонированная матрица алгебраических дополнений

$\Delta A$ - Определитель матрицы A

1) $\Delta A$ мы посчитали задачей выше, он = 60

2) Считаем $A_*$ - для этого считаем матрицу миноров и умножаем миноры на алгебраическое дополнение $(-1)^{i+j}$

$M_{11} = \begin{bmatrix}0 & 6 \\ 8 & 9 \\\end{bmatrix} = 0 \cdot 9 - 6 \cdot 8 = -48 \Rightarrow A_{*11} = (-1)^{1+1} \cdot (-48) = -48$

$M_{12} = \begin{bmatrix}4 & 6 \\ 7 & 9 \\\end{bmatrix} = 4 \cdot 9 - 6 \cdot 7 = -6 \Rightarrow A_{*12} = (-1)^{1+2} \cdot (-6) = 6$

$M_{13} = \begin{bmatrix}4 & 0 \\ 7 & 8 \\\end{bmatrix} = 4 \cdot 8 - 0 \cdot 7 = 32 \Rightarrow A_{*12} = (-1)^{1+3} \cdot 32 = 32$

$M_{21} = \begin{bmatrix}2 & 3 \\ 8 & 9 \\\end{bmatrix} = 2 \cdot 9 - 3 \cdot 8 = -6 \Rightarrow A_{*21} = (-1)^{2+1} \cdot (-6) = 6$

$M_{22} = \begin{bmatrix}1 & 3 \\ 7 & 9 \\\end{bmatrix} = 1 \cdot 9 - 3 \cdot 7 = -12 \Rightarrow A_{*22} = (-1)^{2+2} \cdot (-12) = -12$

$M_{23} = \begin{bmatrix}1 & 2 \\ 7 & 8 \\\end{bmatrix} = 1 \cdot 8 - 2 \cdot 7 = -6 \Rightarrow A_{*23} = (-1)^{2+3} \cdot (-6) = 6$

$M_{31} = \begin{bmatrix}2 & 3 \\ 0 & 6 \\\end{bmatrix} = 2 \cdot 6 - 3 \cdot 0 = 12 \Rightarrow A_{*31} = (-1)^{3+1} \cdot 12 = 12$

$M_{32} = \begin{bmatrix}1 & 3 \\ 4 & 6 \\\end{bmatrix} = 1 \cdot 6 - 3 \cdot 4 = -6 \Rightarrow A_{*32} = (-1)^{3+2} \cdot (-6) = 6$

$M_{33} = \begin{bmatrix}1 & 2 \\ 4 & 0 \\\end{bmatrix} = 1 \cdot 0 - 2 \cdot 4 = -8 \Rightarrow A_{*33} = (-1)^{3+3} \cdot (-8) = -8$

$A_* = \begin{bmatrix}
-48 & 6 & 32 \\
6 & -12 & 6 \\
12 & 6 & -8 \\
\end{bmatrix}$

транспонируем полученную матрицу:

$A_*^T = \begin{bmatrix}
-48 & 6 & 12 \\
6 & -12 & 6 \\
32 & 6 & -8 \\
\end{bmatrix}$

тогда $A^{-1} = \frac{A_*^T}{\Delta A} = 
\frac{
\begin{bmatrix}
-48 & 6 & 12 \\
6 & -12 & 6 \\
32 & 6 & -8 \\
\end{bmatrix}}{60} = 
\begin{bmatrix}
-0.8 & 0.1 & 0.2 \\
0.1 & -0.2 & 0.1 \\
0.53(3) & 0.1 & -0.13(3) \\
\end{bmatrix}
$

Проверим на Python и убедимся, что всё ок и норм:

In [9]:
print(f'матрица A =\n{A}\n\nа обратная матрица =\n{np.linalg.inv(A)}')

матрица A =
[[1 2 3]
 [4 0 6]
 [7 8 9]]

а обратная матрица =
[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


**1) Приведите пример матрицы 4х4, ранг которой равен 1.**

У матрицы с одинаковыми элементами первый $\Delta \neq 0$, тогда как остальные её $\Delta = 0$

$\Rightarrow$ в качестве ответа подойдёт любая матрица с одинаковыми числами, кроме нулевой, так как у нулевой все $\Delta = 0$

In [10]:
C = np.array([[55, 55, 55, 55] for _ in range(4)])
print(f'матрица C =\n{C}\n\nа её ранг = {np.linalg.matrix_rank(C)}')

матрица C =
[[55 55 55 55]
 [55 55 55 55]
 [55 55 55 55]
 [55 55 55 55]]

а её ранг = 1


## 5.4.

**Вычислите скалярное произведение двух векторов:  (1, 5)  и  (2, 8)**

считаем по формуле: $\overrightarrow{A} \cdot \overrightarrow{B} = x_1x_2 + y_1y_2 + z_1z_2$

$\overrightarrow{A} = (1, 5)$

$\overrightarrow{B} = (2, 8)$

$\overrightarrow{A} \cdot \overrightarrow{B} = (1 \cdot 2) + (5 \cdot 8) = 2 + 40 = 42$

проверим за собой на Python:

In [11]:
a = np.array([1, 5])
b = np.array([2, 8])
np.dot(a, b)

42

## 5.5.

**(1, 5, 0), (2, 8, 7) и (7, 1.5, 3) Вычислите смешанное произведение трех векторов:**

будем комбинировать скалярное и векторное произведения, причём соглавно правилу $(\overrightarrow{A} \times \overrightarrow{B}) \cdot \overrightarrow{C} = \overrightarrow{A} \cdot (\overrightarrow{B} \times \overrightarrow{C})$ не имеет значения, какими векторами проводить скалярное произведение, а с какими смешанное. В итоге мы получим скаляр

$\overrightarrow{A} = (1, 5, 0)$

$\overrightarrow{B} = (2, 8, 7)$

$\overrightarrow{D} = (7, 1.5, 3)$

1) сначала вычисляем векторное произведение векторов $\overrightarrow{A}$ и $\overrightarrow{B}$

$\overrightarrow{D} = \overrightarrow{A} \times \overrightarrow{B} = \begin{bmatrix}
1 & 5 & 0 \\
2 & 8 & 7 \\
\end{bmatrix} = (5 \cdot 7 - 0 \cdot 8) - (1 \cdot 7 - 0 \cdot 2) + (1 \cdot 8 - 5 \cdot 2) = (35, \; -7, \; -2)$

2) вторым шагом вычисляем скалярное произведение $\overrightarrow{C}$ и получившегося $\overrightarrow{D}$

$\overrightarrow{C} \cdot \overrightarrow{D} = 7 \cdot 35 + 1.5 \cdot (-7) + 3 \cdot (-2) = 245 - 10.5 - 6 = 228.5$

проверим за собой на Python:

In [12]:
A = np.array([1, 5, 0], float)
B = np.array([2, 8, 7], float)
C = np.array([7, 1.5, 3])
print(f'вектор A = {A}\nвектор B = {B}\nвектор C = {C}\n\nих смешанное произведение = {np.inner(np.cross(A, B), C)}')

вектор A = [1. 5. 0.]
вектор B = [2. 8. 7.]
вектор C = [7.  1.5 3. ]

их смешанное произведение = 228.5
